### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by arthubhub** [arthubhub/Multiarch-PwnBox#7]
`docker-compose.yml` :
```
version: '3.8'

services:
  multiarch-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: multiarch-dev
    volumes:
      - ./shared:/shared
    stdin_open: true
    tty: true
    working_dir: /shared
    command: tmux new-session -A -s pwnbox /root/init
    restart: "no"
```

Execution :
`docker-compose run --rm multiarch-dev`
